language: "en"
task description: "I will fetch you {object_class}."
next location: "I am going to the next location."
next location detailed: "I am going to look in {location} next."
next location detailed ongoing: "I haven't found {object_class} yet. I am going to look in {location} next."
found object: "I have found {object_class}."
found object grasp: "I have found {object_class}. I will try to pick it up."
grasp successful: "I have picked up {object_class}."
and: "and"
trajectory summary start: "I went to"
location not accesible clause: "(which I couldn't access)"
location object found clause: "(where I found {object_class})"
grasp failed summary: "I couldn't pick up {object_class}."
returning to user: "I will go back to the user."
deliver object: "Here is {object_class}."
task outcome failure: "I could not bring you {object_class}."
object not found: "I could not find {object_class}."
object not found unreachable locations: "I could not find {object_class}, but I wasn't able to reach some locations and {object_class} might be there."
object cannot grasp: "I wasn't able to grasp {object_class}. Sorry!"
object unknown: "I don't know how to bring you {object_class}. Try another object."
retry grasp: "I couldn't grasp {object_class}. I will try again."
initial_plan_medium: "I will fetch you {object_class}. I will start looking for it in {location}."
initial_expectations_failure: "I will fetch you {object_class}. I can usually do it, but sometimes I could fail to pick up {object_class} or my way could be blocked."
object_class:
  cup: "the cup"
  bottle: "the bottle"
  remote: "the remote"
  apple: "the apple"
  banana: "the banana"
  wine glass: "the glass"
  oven: "the oven"
  orange: "the orange"
location:
  kitchen: "the kitchen"
  bedroom: "the bedroom"
  table: "the table"
  lounge: "the living room"