language: "es"
task description: "Voy a buscar {object_class}."
next location: "Voy a la siguiente ubicación."
next location detailed: "El próximo lugar en el que buscaré es {location}."
next location detailed ongoing: "Aún no he encontrado {object_class}. Seguiré buscando en {location}."
found object: "He encontrado {object_class}."
found object grasp: "He encontrado {object_class}. Intentaré coger {object_class}."
grasp successful: "He cogido {object_class}."
and: "y"
trajectory summary start: "Fui a los siguientes lugares:"
location not accesible clause: "(donde no pude acceder)"
location object found clause: "(donde encontré {object_class})"
grasp failed summary: "Intenté recoger {object_class} pero fracasé."
returning to user: "Voy a regresar al usuario."
deliver object: "Aquí tienes {object_class}."
task outcome failure: "No pude traer {object_class}."
object not found: "No pude encontrar {object_class}."
object not found unreachable locations: "No pude encontrar {object_class}, pero no he sido capaz de llegar a algunos lugares donde podría buscar {object_class}"
object cannot grasp: "No pude coger {object_class}. Lo siento."
object unknown: "No sé cómo traerte {object_class}. Prueba otro objeto."
retry grasp: "No pude coger {object_class}. Lo intentaré de nuevo."
initial_plan_medium: "Voy a buscar {object_class}. Comenzaré mi búsqueda en {location}."
initial_expectations_failure: "Voy a buscar {object_class}. Normalmente puedo hacerlo, pero a veces podría no detectar {object_class} o mi camino podría estar bloqueado."
object_class:
  cup: "la taza"
  bottle: "la botella"
  remote: "el mando"
  apple: "la manzana"
  banana: "la banana"
  wine glass: "la copa"
  oven: "el horno"
  orange: "la naranja"
location:
  kitchen: "la cocina"
  bedroom: "el dormitorio"
  table: "la mesa"
  lounge: "la sala de estar"